

<CFQUERY NAME="MOVEDIN" DATASOURCE="CENSUS" DBTYPE="ODBC" CACHEDWITHIN="#CreateTimeSpan(0,0,5,0)#">
	SELECT * FROM TENANTS 
	WHERE nUnitNumber = #aUnits[I]# and NHOUSE = 2000
</CFQUERY>

<!--- <CFOUTPUT>#aUnits[I]#</CFOUTPUT> --->
 
<!---  <CFQUERY NAME="MOVEDIN" DATASOURCE="CENSUS" DBTYPE="ODBC" CACHEDWITHIN="#CreateTimeSpan(0,0,5,0)#">
	SELECT * FROM TENANTS WHERE NHOUSE = 2000 and nUnitNumber < 997
</CFQUERY> --->
